---
title: "Komputerowa analiza szeregów czasowych - raport 2"
author: "Szymon Malec, Tomasz Hałas"
output:
  pdf_document: 
    extra_dependencies: ["polski", "mathtools", "amsthm", "amssymb", "icomma", "upgreek", "xfrac", "scrextend", "float", "tabularx", "hyperref", "caption", "enumitem"]
fontsize: 12pt
---

\renewcommand{\figurename}{Wykres}
\renewcommand{\tablename}{Tablica}
\titlelabel{\thetitle.\quad}
\raggedbottom

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE, fig.pos = "H", dev.args=list(encoding="CP1257.enc"))
```

```{r}
library(ggplot2)
library(dplyr)
library(knitr)


regression <- function(X, Y){
    r <- cor(X, Y, use="pairwise.complete.obs")
    Sx <- sd(X)
    Sy <- sd(Y)
    a <- r * Sy / Sx
    b <- mean(Y) - a * mean(X)
    return(c(a, b))
}
```




\section{Wstęp}

|       Celem niniejszej pracy jest wykorzystanie modelu ARMA do zbadanie danych opisujących średnią temperaturę w Warszawie w latach.


\section{Opis danych}




\section{Podsumowanie}

